### PR TITLE
Cmssw 80 x

### PR DESCRIPTION
**Pull request by ralfulrich**
Hi Hans, 

I did not know that I worked so much on CMSS_80X branch....  I used this a lot for 2016 data analysis and we keep using it now for a ZDC-CASTOR combination analysis. This is why I want to push all changes into your main repo. 

Everything should continue to work, I am not aware of any bugs or problems - and I would fix them asap.

Cheers,
Ralf

### CODE REVIEW

**Comment by ralfulrich** [comment]
Please merge since I want to use this a basis for a new analysis together with our Budapest friends.

**Comment by hvanhaev** [comment]
Hi Ralf,

Sorry for the delay, I was in holidays.
Did you provide an alternative for removal of manageCrab3.py script?
I use that when submitting several samples to crab and I don't want to type status several times.

Does any of the core changes imply a different usage of commands/workflow? If yes, please update the twiki documentation also. (And maybe provide a summary here)

Cheers,
Hans

**Comment by ralfulrich** [comment]
Hello Hans,

I was on vacations myself. The script I just removed since I never used
it (and it looked not so useful to me) and I think there are several
scripts that are not needed. But I should not have just deleted it
without checking with you: please just add it again, or I do it later.
Can we maybe review which of the scripts are actually useful in general?

Cheers,
Ralf

**Comment by hvanhaev** [comment]
Hi Ralf,

Thanks, when needed I can add it again in the future, that is fine.
It would indeed be interesting to review the scripts that are obsolete now, or simply not used.
I can have a look and maybe propose some files.

Cheers,
Hans

**Pull request merged**
