### PR TITLE
Added the scripts, README and fixes to allow standalone operation of …

### PR DESCRIPTION
**Pull request by ralfulrich**
Hi Hans,
this is very useful for students who don't have grid account or other people who want to run locally (even on laptop).
Cheers,
Ralf

### CODE REVIEW

**Comment by ralfulrich** [comment]
If this works as expected, we should have this in all branches.

**Comment by hvanhaev** [comment]
Hi Ralf,
Thanks for this development! So this does not destroy running on CMSSW/lxplus installations right? i.e.  removing the FWlite pieces.

Indeed, if it works properly we can add it to all branches.

Cheers,
Hans

**Comment by ralfulrich** [comment]
No, I was running skims with this and there was no change. But I must
say, I don't know what is the real importance of the "AutoLoader". In
principle one could remove this also just for standalone running and
leave it there otherwise. However, for me it seems to make no difference.

Cheers,
ralf

**Comment by hvanhaev** [comment]
Hi Ralf, ok, thanks!

**Pull request merged**
